<?php
echo '
<div class="navbar navbar-fixed-top navbar-inverse">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand pull-left" href="#">Lending Library</a>
 		<div class="nav-collapse navbar-responsive-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="search.html">Search</a></li>
        <li><a href="addItem.html">Add Item</a></li>
        <li><a href="my_items.php">My Items</a></li>
        <li>
			<form id="loginform" method="get" action="https://login.oregonstate.edu/cas/login" class="form-horizontal">
				<fieldset>
					<div id="formfields">
					<!-- Fields will be generated by jquery if user is not logged in -->
					</div>
				</fieldset>
			</form>
		</li>
      </ul>
    </div>
</div> 	<!-- /.navbar -->
';
